## Example: Creating a template for "tidy" data collection

We will walk through an example of creating a template to collect data in a
"tidy" format for a laboratory-based research project, based on a research
project on drug efficacy in murine tuberculosis models. We will show the initial
"untidy" format for data recording and show how we converted it to a "tidy"
format. Finally, we will show how the data can then easily be analyzed and
visualized using reproducible tools.

**Objectives.** After this module, the trainee will be able to:

- Understand how the principles of "tidy" data can be applied for a real, complex research project;
- List advantages of the "tidy" data format for the example project 

### Subsection 1

### Subsection 2

### Example datasets

**Example dataset 1.**

**Example dataset 2.**

### Issues with these data sets

1. Issues related to using a spread sheet program
    - Embedded macros
    - Use of color to encode information
2. Issues related to non-structured / non-two-dimensional data
    - Added summary row
    - Multiple tables in one sheet
    - One cell value is meant to represent values for all rows below, until next
      non-missing row
3. Issues with data being non-"tidy"

### Final "tidy" examples

### Options for recording tidy data

**Spreadsheet program.**

**Spreadsheet-like interface in R.**

### Examples of how "tidy" data can be easily analyzed / visualized




### Discussion questions

