## Creating 'Project' templates

Researchers can use RStudio's 'Projects' can facilitate collecting research
files in a single, structured directory, with the added benefit of easy use of
version control. Researchers can gain even more benefits by consistently
structuring all their 'Project' directories. We will demonstrate how to
implement structured project directories through RStudio, as well as how RStudio
enables the creation of a 'Project' for initializing consistently-structured
directories for all of a research group's projects.

**Objectives.** After this module, the trainee will be able to:

- Be able to create a structured `Project` directory within RStudio
- Understand how RStudio can be used to create 'Project' templates

The last module describe the advantages of organizing all the files for a 
research project within a single file directory, as well as the added 
advantages of making that file directory an RStudio "Project". In this 
module, we'll walk through the steps required to do that, as well as 
how to navigate and use the "Project" structure and functionality to 
make it easier to integrate project files, code, and final output like
reports and presentation slides. If you have created a standardized
file directory structure that you will use as a starting point for all of 
your research projects, then it can save time to create an RStudio Project
Template with this structure. This way, you can set up a new directory, 
including all the subdirectories you want to use and any code or report
templates that might be useful, by just opening a new project with this
template through RStudio. 

### Making an existing file directory an RStudio Project

It's very easy to turn an existing file directory into an RStudio Project. 
Open RStudio, and then in its menu go to "File" and then "New Project". 
This will open a pop-up window with several options, including the option to
create a new RStudio Project from an existing directory. Choose this option, 
and then in the window that is opened, navigate through your file directories
to the directory with your project files. 

This will create a new RStudio Project with the same name as the file directory 
name of the directory you selected [check this]. Once you have created the 
directory, RStudio will automatically move you into that Project. When you 
close RStudio and reopen it, it will automatically open in the last Project
you had open. There is a small tab in the top right hand corner of the RStudio
window that lists the project you are currently in. To move to a different Project, 
you can click on the down arrow beside this project name. There will be a list
of your most recent projects, as well as options to open any Project on your 
computer. If you want to work in RStudio, but not in any of the Projects, you can 
choose to "Close Project".

When you are working in an RStudio Project, RStudio will automatically move your
working directory to be the top-level directory of the Project directory. This
makes it easy to write code that uses this directory as the presumed working 
directory, using relative file paths to identify and files within the directory. 
For example ... . Now if you share the project directory with someone else, they
can similarly open the RStudio Project in their own version of RStudio, and all 
the relative pathnames to files should work on their system without any problems.
This feature helps make code in an RStudio Project directory reproducible across 
different people's computers. 

The RStudio Project environment has some other features, as well, that may be
useful for some projects. For example, if you are tracking the project directory
under the git version control system, then when you open the RStudio Project, 
there will be a special tab in one of the panes to help in using git with the 
project. This tab provides a visual interface for you to commit changes you've made, 
so they are tracked and can be reversed if needed, and also so you can easily 
push and pull these committed changes to and from a remote repository, like a 
GitHub repository, if you are collaborating with others. 

For certain types of projects, you may also want to include a "Makefile". [More
about Makefiles]. If you add this to an RStudio Project, you will get a new
"Build" tab that allows you to run the Makefile for the project with the click of 
a button. For some more complex RStudio Projects, like projects that use RMarkdown
to create online books or websites using `bookdown` and `blogdown`, this "Build" 
pane will allow you to render the whole book. 

### Making an RStudio Project Template

If you have created a template directory for research projects for your group,
you can create an RStudio Project template to make it easy to set up a new
project directory every time you start a project. At its most basic, this can be
a directory that includes the subdirectories (with standardized names for each
subdirectory) that you want to include---for example, you may know that you will
always want the project directory to include subdirectories for "raw_data" (with
its own subdirectories for different types of data, for example for "cfus" and
"flow"), "data" (with clean versions of the data, after conducting and needed
preprocessing, like calculating CFUs in a sample based on data from plating at
different dilutions, or the output from gating flow cytometry data), "reports"
(for writing, posters, and presentation slides), and "R" (for common scripts
that you use for preprocessing, visualization, and data analysis).

As you progress, you may also want to add templates that serve as a starting point
for files within this project. For example, if you always want to collect 
observed data in a standard way, you could create a template for data collection, 
for example as a CSV file. Each researcher in your lab could copy and rename this 
file each time they collect a new set of data---by ensuring a common structure
when collecting the data, including file format, column names, and so on, you can
build code scripts that will work on data collected for all your experiments. You 
may also have some standard reports that you want to create with types of data
you commonly collect, and so you could include templates for those reports in your
R Project template. Again, these can be copied and adapted within the project---the
template serves as a starting point so you don't have to start with a blank slate 
with every project, but it is not restrictive and can be adapted to each project
as you work on that project.

[How to create a template]

### Discussion questions
