## Simplify scripted pre-processing through R's 'tidyverse' tools

The R programming language now includes a collection of 'tidyverse' extension
packages that enable user-friendly yet powerful work with experimental data,
including pre-processing and exploratory visualizations. The principle behind
the 'tidyverse' is that a collection of simple, general tools can be joined
together to solve complex problems, as long as a consistent format is used for
the input and output of each tool (the 'tidy' data format taught in other
modules). In this module, we will explain why this 'tidyverse' system is so
powerful and how it can be leveraged within biomedical research, especially for
reproducibly pre-processing experimental data.

**Objectives.** After this module, the trainee will be able to:

- Define R's 'tidyverse' system 
- Explain how the 'tidyverse' collection of packages can be both user-friendly
and powerful in solving many complex tasks with data
- Describe the difference between base R and R's 'tidyverse'.

### Subsection 1

> "There is a now-old trope in the world of programming. It's called the 'worse is 
better' debate; it seeks to explain why the Unix operating systems (which include
Mac OS X these days), made up of so many little interchangeable parts, were so much
more successful in the marketplace than LISP systems, which were ideologically pure, 
based on a single languagae (again, LISP), which itself was exceptionally simple, 
a favorite of 'serious' hackers everywhere. It's too complex to rehash here, but one
of the ideas inherent within 'worse is better' is thata systems made up of many 
simple pieces that can be roped together, even if those pieces don't share a consistent
interface, are likely to be more successful than systems that are designed with consistency 
in every regard. And it strikes me that this is a fundamental drama of new technologies. 
Unix beat out the LISP machines. If you consider mobile handsets, many of which run
descendants of Unit (iOS and Andriod), Unix beat out Windows as well. And HTML5 beat out
all of the various initiatives to create a single unified web. It nods to accessibility: 
it doesn't get in the way of those who want to make something huge and interconnected.
But it doesn't enforce; it doesn't seek to change the behavior of page creators in the
same way that such lost standards as XHTML 2.0 (which eremged from the offices of 
the World Wide Web Consortium, and then disappeared under the weight of its own
intentions) once did. It's not a bad place to end up. It means that there is no 
single framework, no set of easy rules to lear, no overarching principles that, 
once learned, can make the web appear like a golden statue atop a mountain. There
are just components: HTML to get the words on the page, forms to get people to
write in, videos and images to put up pictures, moving or otherwise, and 
JavaScript to make everything dance." [@ford2015on]

> "One of the fundamental contributions of the Unix system [is] the idea of a *pipe*.
A pipe is a way to connect the output of one program to the input of another program
without any temporary file; a *pipeline* is a connection of two or more programs through
pipes. ... Any program that reads from a terminal can read from a pipe instead; any program
that writes on the terminal can write to a pipe. ... The programs in a pipeline actually 
run at the same time, not one after another. This means that the programs in a pipeline
can be interactive; the kernel looks after whatever scheduling and synchronization is needed
to make it all work. As you probably suspect by now, the shell arranges things when you
ask for a pipe; the individual programs are oblivious to the redirection." [@kernighan1984unix]

> "Even though the Unix system introduces a number of innovative programs and techniques, 
no single program or idea makes it work well. Instead, what makes it effective is an approach
to programming, a philosophy of using the computer. Although that philosophy can't be written
down in a single sentence, at its heart is the idea that the power of a system comes more from
the relationships among programs than from the programs themselves. Many Unix programs do 
quite trivial things in isolation, but, combined with other programs, become general and 
useful tools." [@kernighan1984unix]

> "What is 'Unix'? In the narrowest sense, it is a time-sharing operating system *kernel*:
a program that controls the resources of a computer and allocates them among its users.
It lets users run their programs; it controls the peripheral devices (discs, terminals, 
printers, and the like) connected to the machine; and it provides a file system that 
manages the long-term storage of information such as programs, data, and documents.
In a broader sense, 'Unix' is often taken to include not only the kernel, but also
essential programs like compiles, editors, command languages, programs for copying and
printing files, and so on. Still more broadly, 'Unix' may even include programs
develpoed by you or others to be run on your system, such as tools for document 
preparation, routines for statistical analysis, and graphics packages." [@kernighan1984unix]

### Subsection 2

### Practice quiz

