## RMarkdown for creating reproducible data pre-processing protocols

The R extension package RMarkdown can be used to create documents that combine
code and text in a 'knitted' document, and it has become a popular tool for
improving the computational reproducibility and efficiency of the data analysis
stage of research. This tool can also be used earlier in the research process,
however, to improve reproducibility of pre-processing steps. In this module, we
will provide detailed instructions on how to use RMarkdown in RStudio to create
documents that combine code and text. We will show how an RMarkdown document
describing a data pre-processing protocol can be used to efficiently apply the
same data pre-processing steps to different sets of raw data.

**Objectives.** After this module, the trainee will be able to:

- Define RMarkdown and the documents it can create 
- Explain how RMarkdown can be used to improve the reproducibility of research
projects at the data pre-processing phase
- Create a document in RStudio using RMarkdown
- Apply it to several different datasets with the same format

### RMarkdown

You can easily create and render knitted documents directly in R through RMarkdown
documents. While RMarkdown documents can be created and rendered through any 
implementation of R, there are very nice facilities for creating and working with 
these documents in the RStudio IDE for R, so in this section we'll focus on 
this interface. RStudio is a free IDE that is available for download online. 
You should download and install R before you install the RStudio IDE, but once you
do, the installation of RStudio should be very straightforward. Many of the 
resources for learning R now focus on use of the RStudio IDE as an interface for
R, so there are lots of available resources for learning more about RStudio if you 
are new to this IDE.

...

[More about RMarkdown specifically]

### Creating and rendering RMarkdown documents

In this subsection, we'll cover some of the basics of writing and rendering 
knitted documents in R using RStudio. We will first provide a quick overview
of working with RMarkdown. We will not go into depth on all details of the 
system, since there are excellent resources for learning these details. However, 
we will go over several details that are very helpful but that a lot of people
learning RMarkdown don't realize are available, so you will know they are 
available when you're ready to learn and incorporate them.

[How to create an RMarkdown document]

In the previous module, we described how knitted documents use special markers
to indicate where sections of executable code start and stop. In RMarkdown, 
the markers you will use to indicate executable code look like this: 

````
```r{}
my_object <- c(1, 2, 3)
```
````

The first part of this marker (```` ```r{} ````) indicates that a section of
code is starting. Then end part (```` ``` ````) indicates that the file is
moving back to regular Markdown. In the first marker, you can use the simplest
form (```` ```r{} ````) to indicate the start of the code. However, you can also
include options to customize actions when the code in that section is executed.
For example, you can specify that the code should be printed in the document,
but not executed, by setting the `eval` parameter to `FALSE` with ```` ```{r
eval = FALSE} ```` as the marker to start the code section. Among the other
options that can be included here are options to: 

- specify the image size and output size of figures created by the code
(`fig.width`, `fig.height`, `out.width`, `out.height`)
- suppress messages, warnings, and errors generated when the code is 
executed (`message`, `warning`, `error`)
- specify whether to print the code or not (for a tutorial, you will want
others to be able to see the code as an example, while for a report, you 
might want the reader to focus on the output) (`echo`)

[How to render to Word]

You can chose to render your document to other formats, as well. The two 
main other formats you may consider are HTML and pdf. You can set up these
choices when you first create your RMarkdown document. However, even if you 
set up a document to render to Word, you can change its settings later so 
it will render to these other formats. We'll cover several ways to do this, 
and some other set-up that's require to render a document to pdf, in the
next few paragraphs. 

You can easily render the RMarkdown document to HTML instead of Word by 
changing the output format for the document before you knit it. There are 
a couple of ways you can make this change. First, if you are rendering the 
document in RMarkdown, click on the down arrow directly to the right of 
the "Knit" button. In that pull-down menu, you can select the "Knit to 
HTML" option, and the document will render to HTML. 

You can also change the output format to HTML in a special section at the top of
the RMarkdown document called the "YAML". The YAML is a special section at the
top of an RMarkdown document (the original, plain text file, not the rendered
version). It is set off from the rest of the document using a special
combination of characters, using a process very similar to how executable code
is set off from other text with a special set of characters so it can be easily
identified by the software program that renders the document. For the YAML, this
combination of characters is three hyphens (`---`) on a line by themselves to
start the YAML section and then another three on a line by themselves to end it.
Here is an example of what the YAML might look like at the top of an RMarkdown
document:

````
---
title: "Laboratory report for example project"
author: "Brooke Anderson"
date: "1/12/2020"
output: word_document
---
````

Within the YAML itself, you can specify different options for your document. 
You can change simple things like the title, author, and date, but you can 
also change more complex things, including how the output document is rendered.
For each thing that you want to specify, you specify it with a special 
keyword for that option and then a valid choice for that keyword. The idea 
is very similar to setting parameter values in a function call in R. For 
example, the `title:` keyword is a valid one in RMarkdown YAML. It allows you 
to set the words that will be printed in the title space, using title formatting, 
in your output document. It can take any string of characters, so you can put in 
any text for the title that you'd like, as long as you surround it with quotation 
marks. The `author:` and `date:` keywords work in similar ways. The `output:` 
keyword allows you to specify the output that the document should be rendered to. 
In this case, the keyword can only take one of a few set values, including
`word_document` to output a Word document, `pdf_document` to output a pdf 
document (see later in this section for some more set-up required to make that
work), and `html_document` to output an HTML document. 

As you start using RMarkdown, you will be able to do a lot without messing with the
YAML much. In fact, you can get a long way without ever changing the values
in the YAML from the default values they are given when you first create an 
RMarkdown document. As you become more familiar with R, you may want to learn 
more about how the YAML works and how you can use it to customize your 
document---it turns out that quite a lot can be set in the YAML to do very 
interesting customizations in your final rendered document. The book 
*R Markdown: The Definitive Guide* [ref], which is available free online, has
sections discussing YAML choices for both HTML and pdf output, at 
https://bookdown.org/yihui/rmarkdown/html-document.html and 
https://bookdown.org/yihui/rmarkdown/pdf-document.html, respectively. There is 
also an interesting talk available online that Yihui Xie, the creator of RMarkdown, 
gave on this topic at a past RStudio conference, available at 
https://rstudio.com/resources/rstudioconf-2017/customizing-extending-r-markdown/. 

If you'd like to render the output document to pdf, the process is similar, but
it will require you to download an additional piece of (free) software. RStudio
uses a program based on a software program called TeX to render RMarkdown 
documents to pdf. You will need to get different software depending on the 
operating system (OS) of your computer. If you are using a Mac OS, then you should 
download [MacTex---more on this], while if you are using a Windows OS, then you
should download [MicTex---more on this]. [More info on getting this software---don't
select the lightweight option, etc.] Once you've installed this software, restart
your RStudio session to help RStudio identify the new program as it starts 
[is this necessary?].

Once you've installed an implementation of TeX, you can use the same process
to change the output format for an RMarkdown document to pdf as you can to change
to HTML---either change the selected output format in the pull-down menu accessed
with the arrow to the right of the "Knit" button, or change the output format
in the YAML of the RMarkdown document [to ...?].

### Some helpful additional features in RMarkdown

The previous subsection gave an overview of the basics of creating and 
rendering a document with RMarkdown. We gave just an overview, as there are 
many resources for learning and practicing RMarkdown that are available, including
many that are freely available online. In this sections, we'll point you to 
some of those resources. 

To learn more about RMarkdown, you can explore a number of excellent resources.
The most comprehensive are shared by RStudio, where RMarkdown's developer
and maintainer, Yihui Xie, works. These resources are all freely available 
online, and some are also available to buy as print books, if you prefer that
format. 

First, you should check out the online tutorials that are provided by RStudio on
RMarkdown. These are available at RStudio's RMarkdown page:
https://rmarkdown.rstudio.com/. The page's "Getting Started" section 
(https://rmarkdown.rstudio.com/lesson-1.html) provides a nice introduction 
you can work through to try out RMarkdown and practice the overview provided
in the last subsection of this module. The "Articles" section 
(https://rmarkdown.rstudio.com/articles.html) provides a number of other 
documents to help you learn RMarkdown.

RStudio's RMarkdown page also includes a "Gallery"
(https://rmarkdown.rstudio.com/gallery.html). This resource allows you to browse
through example documents, so you can get a visual idea of what you might want
to create and then access the example code for a similar document. This is a 
great resource for exploring the variety of documents that you can create 
using RMarkdown.

To go more deeply into RMarkdown, there are two online books from some of the
same team that are available online. The first is *R Markdown: The Definitive
Guide* by Yihui Xie, J. J. Allaire, and Garrett Grolemund [ref for this book]. 
This book is available at https://bookdown.org/yihui/rmarkdown/. It moves from 
basics through very advanced functionality that you can implement with RMarkdown, 
including several of the topics we highlight later in this subsection. 

The second online book to explore from this team is *R Markdown Cookbook*, 
by Yihui Xie, Christophe Dervieux, and Emily Riederer. This book is a helpful 
resource for dipping in to a specific section when you want to learn how to 
achieve a specific task. Just like a regular cookbook has recipes that you can
explore and use one at a time, this book does not require a comprehensive
end-to-end read, but instead provides "recipes" with advice and instructions
for doing specific things. For example, if you want to figure out how to 
align a figure that you create in the center of the page, rather than the 
left, you can find a "recipe" in this book to do that.

### Some helpful additional features in RMarkdown

Some of the references mentioned in the last subsection are very comprehensize.
Therefore, in this section, we'll point out and briefly overview several
features that you might not be introduced to in introductory RMarkdown
tutorials, but we have found can be very useful for researchers who are using
RMarkdown to document their code for scientific projects. You can find more
details about these in the references given in the last subsection, so in this
subsection, our aim is to help make you aware that these resources are available
if you need them and to point you to places where you can find out more. 

[How to extract just the code from the document]

[How to include references using BibTex as a reference manager]

[How to include formulas and math]

In your RMarkdown documents, you include executable code in special sections
("chunks") that are separated from the regular text using a special combination
of characters. By default, the code in these chunks are executed using the 
R programming language. However, you can also include executable code in a 
number of other programming languages. For example, you could set some code
chunks to run Python, others to run Julia, and still others to run a 
shell script [?].

This can be very helpful if you have steps in you Python that use code in 
different languages. For example, there may be a package [?] in Python that
works well for an early step in your data preprocessing, and then later 
steps that are easier with general R functions. This presents no problem in 
creating an RMarkdown data pre-processing protocol, as you can include 
different steps using different languages. 
 
The program that is used to run the code in a specific chunk is called the 
"engine" for that chunk [?]. You can change the engine [where in the code
chunk markup]. [More on this.] When your RMarkdown document is rendered, 
your computer will use the specified software to run each code chunk. Of course, 
to run that piece of code, your computer must have that type of software installed
and available. For example, if you include a chunk of code that you'd like to 
run with a Python engine, you must have Python on your computer.

While you can use many different software programs as the engine for each code
chunk, there are a few limitations with some programs. For many open-source 
software programs, the results from running a chunk of code with that engine
will be available for later code chunks to use as an input. This is not the case, 
however, for some proprietary software [?]. For example, if you use the SAS software
program as the engine for one of your code chunks, the output from running that code
will not be available to input to later code in the document [?].

Some code can take a while to run, particularly if it is processing very large
datasets. By default, RMarkdown will re-run all code in the document every time
you render it. This is usually the best set-up, since it allows you to confirm
that the code is all executing as desired each time the code is rendered.
However, if you have steps that take a long time, this can make it so the
RMarkdown document takes a long time to render each time you render it.

To help with this problem, RMarkdown has a system that allows you to *cache*
results from some or all code chunks in the document. This is a really nice
system---it will check the inputs to that part of the code each time the
document is run. If those inputs have changed, it will take the time to re-run
that piece of code, to use the updated inputs. However, if the inputs have not
changed since the last time the document was rendered, then the last results for
that chunk of code will be pulled from memory and used, without re-running the
code in that chunk. This saves time most of the times that you render the
document, while taking the time to re-run the code when necessary, because the
inputs have changed and so the outputs may be different.

[More on caching from RMarkdown, including things to look out for, like the size
of the document as it grows to include cached values.]

[Using journal article templates]


You can use RMarkdown to create documents other than traditional reports. 
Scientists might find the outputs of presentations and posters particularly 
useful. 

RMarkdown has allowed a pdf slide output for a long time. This output leverages
the "beamer" format from LaTeX. You can create a series of presentation slides
in RMarkdown, using Markdown to specify formatting, and then the document will
be rendered to pdf slides. These slides can be shown using a pdf viewer [?],
like Adobe Acrobat, set either to full screen or to the presentation option [?].
More recently, capability has been added to RMarkdown that allows you to create
PowerPoint slides. Again, you will start from an RMarkdown document, using
Markdown syntax to do thinks like divide content into separate slides.
Regardless of the output format you choose (pdf slides or PowerPoint), the code
to generate figures and tables in the presentation can be included directly in
the RMarkdown, so it is re-run with the latest data each time you render the
presentation.

[Where to find out more about creating presentations with RMarkdown]

It is also possible to use RMarkdown to create scientific posters, although this
is a bit less common and there are fewer tutorial resources with instructions on
doing this. [More on making posters with RMarkdown. Some examples on GitHub.]

It is very easy to add figures and simple tables to RMarkdown documents, and 
this process is covered thoroughly in basic tutorials on RMarkdown. However, 
as you start using RMarkdown more and more, and want to use it to create 
article drafts, posters, and presentations, you may want to create more 
customized tables. 

There is an R package that allows you to create very attractive and complex
tables in RMarkdown documents. This package leverages more of the power of
underlying markdown languages, rather than the simpler Markdown language. If you
remember, Markdown is pretty easy to learn because it has a somewhat limited set
of special characters and special markings that you can use to specify
formatting in your output document. This basic set of functionality is often all
you need, but for complex table formatting, you will need more. There is much
more available in the deeper markup languages that you can use specifically to
render pdf documents (software derived from TeX) and the one that you can use
specifically to render HTML (the HTML markup language---the "ML" in "HTML", in
fact, stand for "Markup Language" [?]).

As a result, you will need to create RMarkdown files that are customized to a
single output format (pdf or HTML) to take advantage of this package. The
package is called `kableExtra`. You can install it the same as any other R
package from CRAN, using `install.packages`. You will need to use then need to
use `library("kableExtra)` within your RMarkdown document before you use
functions from the package. The `kableExtra` package is extensively documented
through two vignettes that come with package, one if the output will be in pdf
and one if it will be in HTML: [websites for these vignettes]. There is also
information on using `kableExtra` available through [RMarkdown book. doublecheck
which one. Cookbook?]

You can use RMarkdown to create much larger outputs, compared to simpler reports
and protocols. RMarkdown can now be used to create very large and dynamic documents, 
including online books (which can also be rendered to pdf versions suitable for 
printing), dashboard-style websites, and blogs. Once members of your research 
group are familiar with the basics of RMarkdown, you may want to explore using 
it to create these more complex outputs. The book format divides content into 
chapters and special sections like appendices and references. It includes a 
table of contents based on weblinks, so readers can easily navigate the content. 
It uses a book format as its base that allows readers to do things like change the 
font size and search the book text for keywords. The blog format allows you to 
create a very attractive website that includes a blog section, where you can 
write and regularly post new blogs, keeping the site dynamic. There are templates
for these blogs that are appropriate for creating personal or research group 
websites for academics. The dashboard format is excellent for creating a webpage
that allows users to view complex, and potentially interactive, results from 
data you've collected. It can be particularly helpful for groups that need to 
quickly communicate regularly updated data to viewers. During 2020, for example, 
many public health departments maintained dashboard-style websites to share 
evolving data on COVID-19 in the community.

Using RMarkdown in this case has two key advantages. First, you can include
executable R code in any of these documents if you create them with RMarkdown.
This will allow you to put example code in the document and ensure that it is
working correctly. It also allows you to easily update documents as you get new
or updated data, since it is easy to re-run any data processing, analysis, and
visualization code in the document.

There are several thorough references that you can use to learn more about creating
the larger output documents using RMarkdown. Online books can be created using the
package `bookdown`. There is an online book available with extensive instructions on 
using this package, available at [weblink to bookdown book]. There is also a helpful
website with more details on this package, bookdown.org [put in full webline here].
The website include a gallery of example books created with bookdown [link for this], 
which you can use to explore the types of books that can be created. There are also 
online video tutorials [?], available at ....

To learn how to create websites with blogs, you can check the book *blogdown* [check 
title, add ref], which is available both in print and free online at [weblink]. This
process takes a bit of work to initially get the website set up, but then allows for 
easy and straightforward maintenance. [Gallery with example websites?]. These 
websites can be created to highlight the research and people in your research lab. 
You can encourage students and postdocs to create personal sites, to raise the profile
of their research. In the past, we have even used one as a central, unifying spot
for a group study or other course [link to our course website for the group study].

### Using RMarkdown to improve reproducibility in data pre-processing



### Subsection 1

> "WordPerfect was always the best word processor. Because it allowed for insight into
its very structure. You could hit a certain key combination and suddenly the screen
would split and you'd reveal the codes, the bolds and italics, and so forth, 
that would define your text when it was printed. It was beloved of legal secretaries
and journalists alike. Because when you work with words, at the practical, everyday
level, the ability to look under the hood is essential. Words are not simple. And
WordPerfect acknowledged that. Microsoft Word did not. Microsoft kept insisting that
what you saw on your screen was the way things *were*, and if your fonts just kept
sort of randonmly changing, well, you must have wanted it that way. Then along came 
HTML, and what I remember most was that sense of being back inside the file. Sure, 
HTML was a typographic nightmare, a bunch of unjustified Times New Roman in 12 pt on 
screens with chiclet-size pixels, but under the hood you could see all the pieces. 
Just like WordPerfect. That transparency was a wonderful thing, and it renewed
computing for me." [@ford2015on]

> "TeX was created by Donald E. Knuth, a professor at Stanford University who has
achieved international renown as a mathematician and computer scientist.
Knuth also has an aesthetic sense uncommon in his field, and his work output is
truly phenomenal. TeX is a happy byproduct of Knuth's mammoth enterprise, 
*The Art of Computer Programming*. This series of reference books, designed
to cover the whole gamut of programming concepts and techniques, is a 
*sine qua non* for all computer scientists." [@seroul2012beginner]

> "Roughly speaking, text processors fall into two categories:
(1) WYSIWYG systems: what you see is what you get. You see on the screen at all
times what the printed document will look like, and what you type has immediate
effect on the appearance of the document. (2)  markup systems, where you type your text 
interspersed with formatting instructions, but don't see their effect right away. You must run a program to examine the
resulting image, whether on paper or on the screen. In computer science jargon,
markup systems must compile the source file you type.  WYSIWYG systems have the obvious 
advantage of immediate feedback, but they
are not very precise: what is acceptable at a resolution of 300 dots per inch, for an
ephemeral publication such as a newsletter or flier, is no longer so for a book that
will be phototypeset at high resolution. The human eye is extraordinarily sensitive:
you can be bothered by the appearance of a text without being able to pinpoint why,
just as you can tell when someone plays the wrong note in an orchestra, without
being able to identify the CUlprit. One quickly leams in typesetting that the beauty,
legibility and comfortable reading of a text depend on minute details: each element
must be placed exactly right, within thousandths of an inch. For this type of work,
the advantage of immediate feedback vanishes: fine details of spacing, alignment,
and so on are much too small to be discernible at the screen's relatively low 
resolution, and even if it such were not the case, it would still be a monumental chore
to find the right place for everything by hand. For this reason it is not surprising that in the world of professional typesetting
markup systems are preferred. They automate the task of finding the right place
for each character with great precision. Naturally, this approach is less attractive for
beginners, since one can't see the results as one types, and must develop a feeling
for what the system will do. But nowadays, you can have the best of both worlds
by using a markup system with a WYSIWYG *front end*; we'll talk about such front
ends for TEX later on. TEX was developed in the late seventies and early eighties, 
before WYSIWYG systems were widespread. But were it to be redesigned now, it would 
still be a markup
language. To give you an idea of the precision with which TEX operates: the internal 
unit it uses for its calculations is about a hundred times smaller than the
wavelength of visible light! (That's right, a hundred times.) In other words, any
round-off error introduced in the calculations is invisible to the naked eye." 
[@seroul2012beginner]

> "You should be sure to understand the difference between a text editor and a text
processor. A text processor is a text editor together with formatting software that
allows you to switch fonts, do double columns, indent, and so on. A text editor
puts your text in a file on disk, and displays a portion of it on the screen. It doesn't
format your text at all. We insist on the difference because those accustomed to WYSIWYG systems are
often not aware of it: they only know text processors. Where can you find a text
editor? Just about everywhere. Every text processor includes a text editor which
you can use. But if you use your text processor as a text editor, be sure to save your
file using a 'save ASCII' or 'save text only' option, so that the text processor's own
formatting commands are stripped off. If you give TEX a file created without this
precaution, you'll get garbage, because TEX cannot digest your text processor's
commands." [@seroul2012beginner]

> "TeX enabled authors to encode their precise intent into their manuscripts:
This block of text is a computer program, while this word is a keyword in that
program. The language it used, called TeX markup, formalized the slow,
error-prone communication that is normally carried out with the printer over
repeated galley proofs." [@apte2019lingua]

> "The idea of writing markup inside text wasn’t especially novel; it has been
used from 1970’s runoff (the UNIX family of printer-preparation utilities) to
today’s HTML tags. TeX was new in that it captured key concepts necessary for
realistic typesetting and formalized them." [@apte2019lingua]

> "With these higher-level commands, the free TeX engine, and the LaTeX book,
the use of TeX exploded. The macro file has since evolved and changed names, but
authors still typically run the program called latex or its variants. Hence,
most people who write TeX manuscripts know the program as LaTeX and the commands
they use as LaTeX commands." [@apte2019lingua]

> "The effect of LaTeX on scientific and technical publishing has been profound.
Precise typesetting is critical, particularly for conveying concepts using
chemical and mathematical formulas, algorithms, and similar constructs. The
sheer volume of papers, journals, books, and other publications generated in the
modern world is far beyond the throughput possible via manual typesetting. And
TeX enables automation without losing precision. Thanks to LaTeX, book authors
can generate camera-ready copy on their own. Most academic and journal
publishers accept article manuscripts written in LaTeX, and there’s even an open
archive maintained by Cornell University where authors of papers in physics,
chemistry, and other disciplines can directly submit their LaTeX manuscripts for
open viewing. Over 10,000 manuscripts are submitted to this archive every month
from all over the world." [@apte2019lingua]

> "For many users, a practical difficulty with typesetting using TeX is
preparing the manuscripts. When TeX was first developed, technical authors were
accustomed to using plain-text editors like WordStar, vi, or Emacs with a
computer keyboard. The idea of marking up their text with commands and running
the manuscript through a typesetting engine felt natural to them. Today’s
typesetters, particularly desktop publishers, have a different mental model.
They expect to see the output in graphical form and then to visually make edits
with a mouse and keyboard, as they would in any WYSIWYG program. They might not
be too picky about the quality of the output, but they appreciate design
capabilities, such as the ability to flow text around curved outlines. Many
print products are now produced with tools like Microsoft Word for this very
reason. TeX authors cannot do the same work as easily." [@apte2019lingua]

> "Poor documentation can lead to irreproducibility and serious errors. There's
a vast amount of lurking complexity in bioinformatics work: complex workflows, 
multiple files, countless program parameters, and different software versions.
The best way to prevent this complexity from causing problems is to document
everything extensively. Documentation also makes your life easier when you need to 
go back and rerun an analysis, write detailed methods about your steps for a 
paper, or find the origin of some data in a directory." [@buffalo2015bioinformatics]




### Subsection 2

### Applied exercise

