--- 
title: "Improving the Reproducibility of Experimental Data Recording and Pre-Processing"
subtitle: "Training modules for laboratory-based researchers"
author: "Brooke Anderson, Michael Lyons, Mercedes Gonzalez-Juarrero, Marcela Henao-Tamayo, and Gregory Robertson"
site: bookdown::bookdown_site
output:
  bookdown::tufte_html_book:
    toc: yes
    css: toc.css
    tufte_variant: "envisioned"
  bookdown::tufte_book2:
    toc: yes
    includes:
      in_header: preamble.tex
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Online book with modules for improving the reproducibility of experimental data recording and preprocessing."
---

```{r include = FALSE}
library(tufte)
library(knitr)
```

# Introduction

`r newthought("Here we will")` introduce the purpose of the book, and maybe put
in the figure with tracks people might want to take.

Click on the **Next** button (or navigate using the
links at the top of the page) to continue.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'ggplot2', 'readr',
  'forcats', 'magrittr', 'dplyr', 'sf', 'htmlwidgets', 'DT', 'plotly', 
  'leaflet', 'flexdashboard'
), 'packages.bib')
```

